### ISSUE TITLE
Provide Scarb package

### ISSUE THREAD

**Issue by mkaput** [OpenZeppelin/cairo-contracts#621]
We'd like to allow users to use OpenZeppelin contracts in Scarb-based projects. Primarily, this means all Protostar projects as it will soon use Scarb for dependency management exclusively.

**📝 Details**

Actually as far as I see, your `Makefile` flow could be easily swapped with Scarb-based solution, when Scarb will come with a test runner and starknet libfuncs verification solution. Both being on track for implementation soon. Am I right?

We also bootstrapped a commercial project that is kinda blocked on this.

**🔢 Code to reproduce bug**

A following Scarb.toml incantation should work:

```toml
[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
```

---

If you'd like, we can help with setting this up.
