### ISSUE TITLE
Use `develop` as main working branch

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#894]
Although our docs and official messaging insist in using a version tag when installing the library, some people (maybe many) don't.

```toml
[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.1" }
```

To be fair, it's ver easy not to. I therefore suggest we start pairing `main` to the latest release and switch to `develop` as our working branch in the spirit of making our stuff as hard to mess up with as possible. The change needs to be documented in our [CONTRIBUTING](https://github.com/OpenZeppelin/cairo-contracts/blob/main/CONTRIBUTING.md) guide.
